src/ViewComponents/FeedViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using dotnetfoundation.Services;
using dotnetfoundation.Models;

namespace dotnetfoundation.ViewComponents
{
    public class FeedViewComponent : ViewComponent
    {
        private readonly RssFeedService feedService;

        public FeedViewComponent(RssFeedService feedService)
        {
            this.feedService = feedService;
        }

        public async Task<IViewComponentResult> InvokeAsync(string url, string view, int quantity)
        {
            var feed = await feedService.GetFeed(url);
            var items = feed.Take(quantity);

            return View(view, items);
        }
    }
}

src/ViewComponents/MeetupViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using dotnetfoundation.Services;
using dotnetfoundation.Models;

namespace dotnetfoundation.ViewComponents
{
    public class MeetupViewComponent : ViewComponent
    {
        private readonly MeetupFeedService meetupService;

        public MeetupViewComponent(MeetupFeedService meetupService)
        {
            this.meetupService = meetupService;
        }

        public async Task<IViewComponentResult> InvokeAsync(int quantity, int descriptionLength)
        {
            var feed = await meetupService.GetFeed();
            var items = feed.Events.Take(quantity);

			var model = (items, descriptionLength);
            return View(model);
        }
    }
}

src/ViewComponents/NewsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using dotnetfoundation.Services;
using dotnetfoundation.Models;

namespace dotnetfoundation.ViewComponents
{
    public class NewsViewComponent : ViewComponent
    {
        private readonly NewsFeedService newsService;

        public NewsViewComponent(NewsFeedService newsService)
        {
            this.newsService = newsService;
        }

        public async Task<IViewComponentResult> InvokeAsync(int quantity)
        {
            var feed = await newsService.GetFeed();
            var items = feed.Take(quantity);

            return View(items);
        }
    }
}

src/Pages/Become-A-Member.cshtml
@page
@using Microsoft.AspNetCore.Mvc.RazorPages

@{
    Layout = "_Layout";
    ViewData["Title"] = "Become a Member of the .NET Foundation";
    ViewData["BodyClass"] = "pages";
}

<section class="page-section page-section--purple">
    <div class="page-section_container container">
        <div class="page-section_row row">
            <div class="page-section_column col-12 text-center">
                <h1>
                    .NET Contributor? Become a member!
                </h1>
                <p>Anyone who has contributed to a .NET Foundation project can apply to become a member.</p>
                <p>Contributions may include code contributions, documentation, or other significant project contribution, including evangelism, teaching, code, organizing events, etc. If in doubt, please ask us at <a href="mailto:contact@dotnetfoundation.org">contact@@dotnetfoundation.org</a>!</p>
            </div>
        </div>
    </div>
</section>

<section class="page-section page-section--purple--light">
    <div class="page-section_container container">
        <div class="page-section_row row h-100">
            <div class="page-section_column col-12 text-left">
                <h2>
                    How to join
                </h2>
                <ul>
                    <li>Any individual contributor to a .NET Foundation project can apply to become a member. 
						Contributions may include code contributions, documentation, or other significant project 
						contribution, including evangelism, teaching, code, organizing events, etc. If in doubt, 
						please ask us at <a href="mailto:contact@dotnetfoundation.org">contact@@dotnetfoundation.org</a>
					</li>
                    <li>Upon approval, members will be notified with information on completing their membership. 
						We’re requesting $100 annual dues, with liberal waivers for students or financial hardship.
						Dues are voluntary - you can set your own amount, or opt-out entirely. We don't track
						individual payment. We don't want dues to be a blocker for anyone who is interested in getting
						involved.
					</li>
                    <li>Each year, we’ll host an election for the board of directors. Any active member can 
						campaign for a one year term, based on their community standing, plans to advance the .NET 
						open source ecosystem, and past performance in case they are seeking reelection.
					</li>
                    <li>Each .NET Foundation member can vote in the election.
					</li>
                </ul>
                <p>
                    Just fill out the form below to let us know how you've contributed to one or more .NET Foundation 
					projects. Please be specific - don't just link to a project, link to individual commits, pull requests, 
					or other individual contributions.
                </p>
                <iframe width="100%" height= "4000px" src= "https://forms.office.com/Pages/ResponsePage.aspx?id=3G8HFsH8FUqxyjLJolWQDu3r3uMrwH1HjiQupxbALB5UN1dWNDJEVlBFWFlKWjc3WTAzSjlWM1JQQS4u&embed=true" frameborder= "0" marginwidth= "0" marginheight= "0" style= "border: none; max-width:100%; max-height:100vh" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </iframe>
            </div>
        </div>
    </div>
</section>

src/Pages/Code-Of-Conduct.cshtml
@page
@using Microsoft.AspNetCore.Mvc.RazorPages

@{
    Layout = "_Layout";
    ViewData["MetaDescription"] = ".NET Foundation Code of Conduct";
    ViewData["Title"] = ".NET Foundation Code of Conduct";
}


<h1 id="contributor-covenant-code-of-conduct">Contributor Covenant Code of Conduct</h1>
<div class="col-md-8">
<h2 id="preamble">Preamble</h2>
<p>The .NET Foundation was created to foster an open, innovative and inclusive community around open source .NET. To clarify expected behaviour in our communities we have&nbsp;adopted the <a href="http://contributor-covenant.org/">Contributor Covenant</a>. This code of conduct has been adopted by&nbsp;<a href="http://contributor-covenant.org/adopters/">many other open source communities</a>&nbsp;and we feel it expresses our values well.&nbsp;</p>
<h2 id="our-pledge">Our Pledge</h2>
<p>We as members, contributors, and leaders pledge to make participation in our community a harassment-free experience for everyone, regardless of age, body size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.</p>
<p>We pledge to act and interact in ways that contribute to an open, welcoming, diverse, inclusive, and healthy community.</p>
<h2 id="our-standards">Our Standards</h2>
<p>Examples of behavior that contributes to a positive environment for our community include:</p>
<ul>
<li>Demonstrating empathy and kindness toward other people</li>
<li>Being respectful of differing opinions, viewpoints, and experiences</li>
<li>Giving and gracefully accepting constructive feedback</li>
<li>Accepting responsibility and apologizing to those affected by our mistakes, and learning from the experience</li>
<li>Focusing on what is best not just for us as individuals, but for the overall community</li>
</ul>
<p>Examples of unacceptable behavior include:</p>
<ul>
<li>The use of sexualized language or imagery, and sexual attention or
advances of any kind</li>
<li>Trolling, insulting or derogatory comments, and personal or political attacks</li>
<li>Public or private harassment</li>
<li>Publishing others&rsquo; private information, such as a physical or email
address, without their explicit permission</li>
<li>Other conduct which could reasonably be considered inappropriate in a
professional setting</li>
</ul>
<h2 id="enforcement-responsibilities">Enforcement Responsibilities</h2>
<p>Community leaders are responsible for clarifying and enforcing our standards of acceptable behavior and will take appropriate and fair corrective action in response to any behavior that they deem inappropriate, threatening, offensive, or harmful.</p>
<p>Community leaders have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, and will communicate reasons for moderation decisions when appropriate.</p>
<h2 id="scope">Scope</h2>
<p>This Code of Conduct applies within all community spaces, and also applies when an individual is officially representing the community in public spaces. Examples of representing our community include using an official e-mail address, posting via an official social media account, or acting as an appointed representative at an online or offline event.</p>
<h2 id="enforcement">Enforcement</h2>
<p>Instances of abusive, harassing, or otherwise unacceptable behavior may be reported to the community leaders responsible for enforcement at <a href="mailto:conduct@dotnetfoundation.org">conduct@dotnetfoundation.org</a>. All complaints will be reviewed and investigated promptly and fairly.</p>
<p>All community leaders are obligated to respect the privacy and security of the reporter of any incident.</p>
<h2 id="enforcement-guidelines">Enforcement Guidelines</h2>
<p>Community leaders will follow these Community Impact Guidelines in determining the consequences for any action they deem in violation of this Code of Conduct:</p>
<h3 id="1-correction">1. Correction</h3>
<p><strong>Community Impact</strong>: Use of inappropriate language or other behavior deemed unprofessional or unwelcome in the community.</p>
<p><strong>Consequence</strong>: A private, written warning from community leaders, providing clarity around the nature of the violation and an explanation of why the behavior was inappropriate. A public apology may be requested.</p>
<h3 id="2-warning">2. Warning</h3>
<p><strong>Community Impact</strong>: A violation through a single incident or series of actions.</p>
<p><strong>Consequence</strong>: A warning with consequences for continued behavior. No interaction with the people involved, including unsolicited interaction with those enforcing the Code of Conduct, for a specified period of time. This includes avoiding interactions in community spaces as well as external channels like social media. Violating these terms may lead to a temporary or permanent ban.</p>
<h3 id="3-temporary-ban">3. Temporary Ban</h3>
<p><strong>Community Impact</strong>: A serious violation of community standards, including sustained inappropriate behavior.</p>
<p><strong>Consequence</strong>: A temporary ban from any sort of interaction or public communication with the community for a specified period of time. No public or private interaction with the people involved, including unsolicited interaction with those enforcing the Code of Conduct, is allowed during this period. Violating these terms may lead to a permanent ban.</p>
<h3 id="4-permanent-ban">4. Permanent Ban</h3>
<p><strong>Community Impact</strong>: Demonstrating a pattern of violation of community standards, including sustained inappropriate behavior,  harassment of an individual, or aggression toward or disparagement of classes of individuals.</p>
<p><strong>Consequence</strong>: A permanent ban from any sort of public interaction within the community.</p>
<h2 id="attribution">Attribution</h2>
<p>This Code of Conduct is adapted from the <a href="https://www.contributor-covenant.org">Contributor Covenant</a>, version 2.0,
available at <a href="https://www.contributor-covenant.org/version/2/0/code_of_conduct.html">https://www.contributor-covenant.org/version/2/0/code_of_conduct.html</a>.</p>
<p>Community Impact Guidelines were inspired by <a href="https://github.com/mozilla/diversity">Mozilla&rsquo;s code of conduct enforcement ladder</a>.</p>
<p>For answers to common questions about this code of conduct, see the FAQ at
<a href="https://www.contributor-covenant.org/faq">https://www.contributor-covenant.org/faq</a>. Translations are available at <a href="https://www.contributor-covenant.org/translations">https://www.contributor-covenant.org/translations</a>.</p>
</div>

src/Pages/Index.cshtml
@page
@using Microsoft.AspNetCore.Mvc.RazorPages

@{
    Layout = "_Layout";
    ViewData["Title"] = ".NET Foundation";
    ViewData["BodyClass"] = "pages";
}
@section Styles{
    <environment names="Development">
       <link rel="stylesheet" href="~/css/home.css" asp-append-version="true">
    </environment>
	<environment names="Staging,Production">
		<link rel="stylesheet" href="~/css/home.css" asp-append-version="true">
		<meta name="google-site-verification" content="F9a3IwT00fpPIErVTvIIqBcf2NEScrDCczZi4g9sul4" />
	</environment>
}

<section id="home-hero">
    <div id="home-hero_container" class="container-fluid d-flex justify-content-center position-relative">
        <div id="home-hero_overlay" class="position-absolute"></div>
        <div id="home-hero_content" class="position-relative">
            <h2 id="home-hero_title">Independent. Innovative. And always open source.</h2>
            <p id="home-hero_copy" class="mx-auto">
                You&apos;ve found the heartbeat of .NET&mdash;where projects and communities come together to get things done in our open-source world. Share your skills for the greater good. Meet in person, get involved virtually, and stay on top of the latest news, meetups, and events.
            </p>
            <div id="home-hero_buttons" class="mx-auto d-flex justify-content-between">
                <a href="https://meetup.com/pro/dotnet" class="home-hero_button site-button site-button--pink">Find a Meetup</a>
                <a href="/projects" class="home-hero_button site-button site-button--pink">Dive into projects</a>
                <a href="/Blog" class="home-hero_button site-button site-button--pink">Get the news</a>
                <a href="/become-a-member" class="home-hero_button site-button site-button--pink">Apply for Membership</a>
            </div>
        </div>
    </div>
</section>
<section class="page-section">
    <div id="home-DATS_container" class="container-fluid d-flex justify-content-left position-relative">
        <a class="home-hero_button site-button site-button--orange float-left" style="margin-left:5%" href="https://devaroundthesun.org/newsletter" target="_blank">Register now!</a>
    </div>
</section>
<section class="page-section">
    <div class="page-section_container container">
        <div class="page-section_row row">
            <div class="page-section_column col-lg-3 col-sm-6">
                <div class="icon-box animated icon-box--grey animation-delay--8 d-flex flex-column align-items-center" data-delay="900">
                    <div class="icon-box_stat counter">
                        61,000
                    </div>
                    <div class="icon-box_icon">
                        <img src="~/img/developers_icon.png">
                    </div>
                    <div class="icon-box_label">
                        Contributors
                    </div>
                </div>
            </div>
            <div class="page-section_column col-lg-3 col-sm-6 pad-fix--sm">
                <div class="icon-box animated icon-box--grey animation-delay--2 d-flex flex-column align-items-center" data-delay="300">
                    <div class="icon-box_stat counter">
                        3700
                    </div>
                    <div class="icon-box_icon">
                        <img src="~/img/building_icon.png">
                    </div>
                    <div class="icon-box_label">
                        Companies
                    </div>
                </div>
            </div>
            <div class="page-section_column col-lg-3 col-sm-6 pad-fix--lg">
                <div class="icon-box animated icon-box--grey animation-delay--4 d-flex flex-column align-items-center" data-delay="500">
                    <div class="icon-box_stat counter">
                        56
                    </div>
                    <div class="icon-box_icon">
                        <img src="~/img/member_projects_icon.png">
                    </div>
                    <div class="icon-box_label">
                        Active Projects
                    </div>
                </div>
            </div>
            <div class="page-section_column col-lg-3 col-sm-6 pad-fix--lg">
                <div class="icon-box animated icon-box--grey animation-delay--6 d-flex flex-column align-items-center" data-delay="700">
                    <div class="icon-box_stat counter">
                        462
                    </div>
                    <div class="icon-box_icon">
                        <img src="~/img/github_icon.png">
                    </div>
                    <div class="icon-box_label">
                        Resources
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="page-section page-section--purple--light">
    <div class="page-section_container container">
        <div class="page-section_row row">
            <div class="page-section_column col-12 text-center">
                <h2>Our main focus? YOU&#8230; and all you do with .NET.</h2>
            </div>
        </div>
        <div class="page-section_row row">
            <div class="page-section_column page-section_column--narrow col-md-4 pad-fix--all text-center">
                <img src="~/img/comp.png">
                <h3>Projects</h3>
                <p>
                    There&apos;s a growing list of projects that are currently taking advantage of our open-source Foundation, benefitting from commercially friendly IP, copyright terms, and licenses.
                </p>
            </div>
            <div class="page-section_column page-section_column--narrow col-md-4 pad-fix--all text-center">
                <img src="~/img/globe_icon.png">
                <h3>Community</h3>
                <p>
                    We work not only with Microsoft, but with the broader industry to increase exposure of .NET&apos;s capabilities. All our resources are designed to support developers and your projects, and help promote your endeavors with like-minded folks!
                </p>
            </div>
            <div class="page-section_column page-section_column--narrow col-md-4 pad-fix--all text-center">
                <img src="~/img/Ellipse_1.png">
                <h3>Non-Profit</h3>
                <p>
                    The .NET Foundation is a 501(c)(6) non-profit organization, which was established to support an innovative, commercially friendly, open-source ecosystem around the .NET platform.
                </p>
            </div>
        </div>
    </div>
</section>
<section class="page-section" id="home-meetup">
    <div class="page-section_container container">
        <div class="page-section_row row">
            <div class="page-section_column col-sm-5 text-center" id="home-meetup_container">
                <h2>.NET Foundation sponsored</h2>
                <img id="home-meetup_image" src="~/img/meetup_logo.png">
                <p>
                    Developers meet every day, across the world, in .NET user groups. <u>Join a group</u>&mdash;or a few!&mdash;to swap knowledge, discover opportunities, or find your next hire.
                </p>
                <div class="site-button_row">
                    <a class="site-button site-button--pink" href="/get-involved#meetups">Find out more</a>
                    <a class="site-button site-button--pink" href="https://meetup.com/pro/dotnet">Join a Meetup</a>
                </div>
            </div>
        </div>
    </div>
    <div style="height: 3rem;"></div>
    <div id="home-meetup_overlay"></div>
</section>
<section class="page-section" id="home-latest">
    <div class="page-section_container container">
        <div class="page-section_row row">
            <div class="page-section_column col-md-6">
                <h2>Upcoming Events and Meetups</h2>
                <vc:meetup quantity="4" description-length="175" />
                <p class="">
                    <a class="link_title" href="https://meetup.com/pro/dotnet">Find more events and Meetups ></a>
                </p>
            </div>
            <div class="page-section_column col-md-6 pad-fix--md">
                <h2>Latest News and Blog</h2>
                <vc:news quantity="5" />
                <p class="">
                    <a class="link_title" href="/news">Get more news ></a>
                </p>
            </div>
        </div>
    </div>
</section>
<section class="page-section" id="home-whiteboard">
    <div class="page-section_container container" id="home-whiteboard_container">
        <div class="page-section_row row">
            <div class="page-section_column page-section_column--narrow col-sm-4 text-center">
                <h2>Build your own event</h2>
                <p>
                    Gearing up for an event of your own? <a href="https://dotnet-presentations.github.io/">Visit our Presentation Library</a> to download FREE workshop materials to get a head start. Browse available resources, including presentations, slides, code, and scripts. We have everything you need to fill a one-hour intro or a full two-day course.
                </p>
                <a class="site-button site-button--pink" href="https://dotnet-presentations.github.io/">Browse resources</a>
            </div>
        </div>
    </div>
    <div id="home-whiteboard_overlay"></div>
</section>
<section id="home-bot" class="page-section page-section--purple">
    <div class="page-section_container container">
        <div class="page-section_row row">
            <div class="page-section_column col-md-1 pad-fix--none">
            </div>
            <div class="page-section_column col-md-4 text-center pad-fix_add--md d-flex align-items-center justify-content-center">
                <img src="~/img/dot_bot.png" id="home-bot_image">
            </div>
            <div class="page-section_column col-md-6 pad-fix--md text-center">
                <h2>Start kicking out code!</h2>
                <p>
                    Have a passion project you&apos;re ready to turn into a reality? A little gem of an idea that you believe in, but haven&apos;t gotten around to?
                </p>
                <p>
                    There&apos;s no time like today to get going. Start your own project, use some code to get traction, and invite fellow coders to bring it to life. It&apos;s more fun with others lending a hand!
                </p>
                <a class="site-button site-button--pink" href="/about">Get started</a>
            </div>
            <div class="page-section_column col-md-1 pad-fix--none">
            </div>
        </div>
    </div>
</section>

@*<partial name="_CookieConsent" />*@

@section Scripts {
    <environment names="Development">
        <script src="~/js/home.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/home.js" asp-append-version="true"></script>
    </environment>

    <script>
        $(function () {
            $(".video-thumbnail").click(function () {
                var videoSrc = $(this).data("videoSrc");
                var thumb = $(this).children('img');
                $(this).replaceWith('<iframe src="' + videoSrc +
                    '" width="' + thumb.width() +
                    '" height="' + thumb.height() + '" allowFullScreen frameBorder="0"></iframe>');
            });
        });
    </script>
}

src/Pages/News.cshtml
@page
@using Microsoft.AspNetCore.Mvc.RazorPages

@{
    Layout = "_Layout";
    ViewData["Title"] = ".NET Foundation News";
    ViewData["BodyClass"] = "pages";
}

<section class="page-section page-section--purple">
    <div class="page-section_container container">
        <div class="page-section_row row">
            <div class="page-section_column col-12 text-center">
                <h1>
                    Chatter to keep up with.
                </h1>
                <p class="mx-auto">
                    This is the page to bookmark. Remember, you, your colleagues, your co-coders in arms &mdash; whether you know them yet or not &mdash; are the ones who make up the community and are the true innovators. So keep an eye on this page for news from us, news about .NET, and most important, updates from your peers. Contributors are commended.
                </p>
            </div>
        </div>
    </div>
</section>

<section class="page-section page-section--main">
    <div class="page-section_container container">
        <div class="page-section_row row">

			<article class="col-md-8">
				<h2>Community News | <a href="/blog">.NET Foundation Blog</a></h2>
				<hr class="page-section_hr">

				<div class="media-list">
					<vc:news quantity="10"></vc:news>
				</div>
			</article>

			<aside class="col-md-4">
				<h2 class="mb-3">Latest tweets</h2>

				<div id="twitter-widget-container">
					<a class="twitter-timeline"
					   style="display:block;min-height:400px;"
					   data-chrome="noheader nofooter"
					   data-tweet-limit="2"
					   href="https://twitter.com/dotnetfdn/likes?ref_src=twsrc%5Etfw">
					</a>
					<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
					<div class="text-right">
						<h4>
							<a href="https://twitter.com/dotnetfdn">More from Twitter ></a>
						</h4>
					</div>
				</div>

				<div>
					<h2 class="page-section_title">Events and Meetups</h2>
					<hr class="page-section_hr">
					<div class="media-list">
						<vc:meetup quantity="3" description-length="120"></vc:meetup>
					</div>
				</div>

				<div class="text-right">
					<h4>
						<a href="https://www.meetup.com/pro/dotnet/">Find more events and Meetups ></a>
					</h4>
				</div>

				<div>
					<h2 class="page-section_title">Featured Project</h2>
					<hr class="page-section_hr">
					<vc:feed quantity="1" url="https://builtwithdot.net/feed/featured?truncateBody=false" view="project"></vc:feed>
				</div>

				<div class="text-right">
					<h4>
						<a href="https://builtwithdot.net">More on BuiltWithDot.Net></a>
					</h4>
				</div>

				<!--

				<div class="page-section_row page-section_row--inner row">
					<div class="page-section_column page-section_column--inner col pad-fix--none" id="news-jobs">
						<h2 class="page-section_title">Job opportunities</h2>

						<hr class="page-section_hr">

						<h3 class="p-title"><a href="">Title of job listing</a></h3>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipisicing el labore et dolore magnam aliquam quaerat voluptatem.
						</p>

						<h3 class="p-title"><a href="">Title of job listing</a></h3>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipisicing el labore et dolore magnam aliquam quaerat voluptatem.
						</p>

						<h3 class="p-title"><a href="">Title of job listing</a></h3>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipisicing el labore et dolore magnam aliquam quaerat voluptatem.
						</p>
					</div>
				</div>
	-->
			</aside>

        </div>
    </div>
</section>
<!--HELLO DOTNET BOT LOVES YOU-->

@section Scripts {
    <script>
        /* Kinda hacky, but Twitter widget doesn't allow CSS customization. May eventually render server-side, but this works. */
        $(function () {
            window.setTimeout(function () {
                var $head = $(".twitter-timeline").contents().find("head");
                $head.append($("<link/>",
                    { rel: "stylesheet", href: "https://fonts.googleapis.com/css?family=Lato", type: "text/css" }
                ));   
                $(".twitter-timeline").contents().find(".timeline-Tweet-text").css({
                    'font-size': '16px',
                    'font-family': 'Lato'
                });
            }, 1000);
        });
    </script>
}